### ISSUE TITLE
Different error types grouped together in honeybadger

### ISSUE THREAD

**Issue by skarabasakis** [Workable/orka#346]
Currently, [honeybadger-appender](https://github.com/Workable/orka/blob/master/src/initializers/log4js/honeybadger-appender.ts#L48) sets a [custom fingerprint](https://docs.honeybadger.io/lib/javascript/guides/customizing-error-grouping/),  forcing all errors originating from the same component and action (e.g. the same api route) to appear grouped together in honeybadger.

For node apps that throw custom errors (i.e. errors that extend `Error`), this has the unfortunate effect of grouping together different errors originating from the same component+action, making it harder to identify and be notified of new error cases. Compare that to ats where different exception types from the same component+action go into different groups ([example](https://app.honeybadger.io/projects/2956/faults?sort=last_seen_desc&q=environment%3A%22production%22%E2%80%81component%3Abackend%2Fapi%2Fjobs%E2%80%81action%3Ads_query)), enabling better visibility for new error cases.

In workable-lite we throw errors with custom names and would like to have a way to group errors by name+component+action rather than just component+action. There does not seem to be a way to achieve this from outside orka. 

Two potential solutions:

**1. Include the error name in the fingerprint**, e.g.

```diff
- `${computedComponent}_${action}`
+ `${error.name}_{computedComponent}_${action}`
```

This change would be backwards-compatible for most node apps that do not bother with custom errors (`error.name == "Error"` in all error cases). But it would be backwards incompatible in the general case.

**2. Allow overriding the fingerprint from outside** 

e.g. by passing a `rest.fingerprint` argument to `notifyHoneybadger`

---

@nikostoulas WDYT? Happy to contribute a PR, which would hopefully make it into orka v4.

cc @jpanagiotidis @kkyriakidis

**Comment by nikostoulas** [comment]
Hey @skarabasakis this is a known limitation of our grouping in HB. Also noted here https://docs.google.com/spreadsheets/d/19otG_tes5flDeBG-1A0oKMlYITcUl_rPtLQan18_FwQ/edit#gid=0.
In the past Manos tried to solve this with this pr https://github.com/Workable/orka/pull/276 but seemed to cause more issues than it solved.

Nice suggestsions!
However I am afraid that 1. solves only part of the problem (e.g. only when using custom errors) and 2. needs to pass fingerprint manually.

1. Would create new errors for everything as the fingerprint would change. We could handle specially the case where error.name == "Error" so that it actually is backwards compatible for those cases. I have no objection in doing this as it seems that it is in the right direction in better grouping errors.

2. Would be backwards compatible so I have no objection in providing a way to manually pass fingerprint from the logger.

**If you have time feel free to contribute both for 1 and 2.** 

If while implementing this you could think anything else that further improves error grouping  so that different errors are not grouped but the similar errors with slightly different messages are let's discuss.
